### PR TITLE
feat: windows support

### PR DESCRIPTION
**Pull request by fredrikaverpil**
This PR introduces a distinction between forward slashes (unix) and backslashes (windows) in filepaths.

However, there's a huge problem with ANSI codes and other stuff is garbling up the JSON output from `go test -json`. Very strange. Only happens on Windows (Powershell). A workaround is to use `gotestsum` as runner, which will then write to JSON file without a console roundtrip:

```bash
# make gotestsum available on $PATH by installing it
go install gotest.tools/gotestsum@latest
```

Then set the (for now undocumented/experimental) `runner` option, and instruct it to use `gotestsum` instead of `go test`:

```lua
  {
    "nvim-neotest/neotest",
    dependencies = {
      "nvim-neotest/nvim-nio",
      "nvim-lua/plenary.nvim",
      "antoinemadec/FixCursorHold.nvim",
      "nvim-treesitter/nvim-treesitter",
      {
        "fredrikaverpil/neotest-golang",
        branch = "windows", -- set PR branch
      },
    },
    config = function()
      require("neotest").setup({
        adapters = {
          require("neotest-golang")({ runner = "gotestsum" }), -- Registration with config
        },
      })
    end,
  },
```

Fixes: #147

### CODE REVIEW

**Comment by fang2hou** [comment]
It is not only Windows Powershell, I also met the problem in macOS.
But after I set the runner to `gotestsum`, everything works great!

**Comment by fredrikaverpil** [comment]
> It is not only Windows Powershell, I also met the problem in macOS.
> 
> But after I set the runner to `gotestsum`, everything works great!

Out of curiosity, which terminal are you on?

**Comment by fang2hou** [comment]
> > It is not only Windows Powershell, I also met the problem in macOS.
> > But after I set the runner to `gotestsum`, everything works great!
> 
> Out of curiosity, which terminal are you on?

I am using Wezterm in macOS.
And I am working with a project with many Japanese characters in the code (test name, comment, some t.Error message, etc.).

**Comment by fredrikaverpil** [comment]
Aha, I see. I would assume it's the Japanese characters that might be causing this. I've been using Wezterm for a long time without any issues, but never with Japanese characters. 😅

Anyway, I'm happy to hear you can use the adapter with the help of `gotestsum`!

**Comment by fredrikaverpil** [comment]
By the way, if you have the possibility, would you mind trying setting the environment variable `LC_ALL=C` (before starting Neovim, so that any `go test` command it spawns will use it) and see if that makes a difference?

**Comment by fredrikaverpil** [comment]
By the way, if you have the time and possibility, would you mind trying setting the environment variable `LC_ALL=C` (before starting Neovim, so that any `go test` command it spawns will use it) and see if that makes a difference?

```bash
export LC_ALL=C
```

**Comment by fang2hou** [comment]
@fredrikaverpil 
The `LC_ALL` is actually not working in my MacBook.
However I also found the following comment, after setting `alias gcc="gcc-14"`, everything works fine.
https://github.com/fredrikaverpil/neotest-golang/issues/193#issuecomment-2362972282

**Pull request merged**
